ITU-BDSA23-GROUP10/Chirp

- src/Chirp.Razor/CheepService.cs
- src/Chirp.Razor/Pages/Public.cshtml
- src/Chirp.Razor/Pages/Public.cshtml.cs
- src/Chirp.Razor/Pages/UserTimeline.cshtml
- src/Chirp.Razor/Pages/UserTimeline.cshtml.cs
As per Helge's updated project description, so now `/?page=1` displays the same content as the homepage, `/`.
> Reverted back to page 1 being the start/homepage.

- GlobalUsings.cs
- src/SimpleDB/SingletonDB.cs
- test/Chirp.CLI.test/GlobalUsings.cs
- test/Chirp.Razor.Tests/GlobalUsings.cs
- test/SimpleDB.test/GlobalUsings.cs
- test/SimpleDB.test/SimpleDB.test.cs
> Decluttering by having file with global usings.

- test/Chirp.Razor.Tests/Chirp.Razor.Tests.csproj
- test/Chirp.Razor.Tests/ChirpRazorHttpClient_UnitTests.cs
- test/Chirp.Razor.Tests/IntegrationTests.cs
Correctly modified integration tests, please review them.
> Further integration tests

- src/SimpleDB/ChirpDBContext.cs
- src/SimpleDB/Migrations/20231013085822_modelconstraints.Designer.cs
- src/SimpleDB/Migrations/20231013085822_modelconstraints.cs
- src/SimpleDB/Models/Author.cs
- src/SimpleDB/Models/Cheep.cs
- test/Chirp.Razor.Tests/Chirp.Razor.Tests.csproj
- test/Chirp.Razor.Tests/InMemoryWebApplicationFactory.cs
- test/Chirp.Razor.Tests/IntegrationTests.cs
> Integration tests with SQLite database stored in-memory

- src/Chirp.Infrastructure/ChirpRepository/AuthorRepository.cs
- src/Chirp.Infrastructure/ChirpRepository/CheepRepository.cs
- src/Chirp.Web/CheepService.cs
- src/SimpleDB/DBFacade.cs
- test/Chirp.Razor.Tests/ChirpUnitTest.cs
- test/Chirp.Razor.Tests/IntegrationTests.cs
This branch should have the necessary unit tests for the new extended repo methods and has moved the conversion from cheeps to CheepDTO objects to where the SQL query calls. 
Resolves #87
> Extended repo tests and dto conversion

- src/Chirp.Web/Pages/Public.cshtml.cs
- src/Chirp.Web/Pages/UserTimeline.cshtml.cs
- src/Chirp.Web/PagesData.cs
- src/Chirp.Web/ViewComponents/PaginationViewComponent.cs
The magic number is only one place now, hurrah.
Resolves #110
> Reduced redundancy by making sure the number 32 only displayed one place.

- src/Chirp.Infrastructure/ChirpRepository/CheepRepository.cs
Added the appropriate code to secure validation when creating cheeps.
Resolves #133
> Validating cheeps on both client and server side

- src/Chirp.Web/Pages/UserTimeline.cshtml
- src/Chirp.Web/Pages/UserTimeline.cshtml.cs
> Added Invalid user error page when trying to access usernames that arent in the system

- src/Chirp.Web/Pages/UserTimeline.cshtml
- src/Chirp.Web/Pages/UserTimeline.cshtml.cs
- test/Chirp.Razor.Tests/IntegrationTests.cs
> Test invalid user error page

- src/Chirp.Core/IAuthorRepository.cs
- src/Chirp.Infrastructure/ChirpRepository/AuthorRepository.cs
- src/Chirp.Infrastructure/ChirpRepository/UserRepository.cs
- src/Chirp.Infrastructure/Models/User.cs
- src/Chirp.Web/Pages/UserProfile.cshtml
- src/Chirp.Web/Pages/UserProfile.cshtml.cs
- src/Chirp.Web/wwwroot/userData/Slug-Boi_UserData.json
This branch solves a couple of leftover tasks that were left from the profile page building branches.
Resolves #196
Resolves #197
Resolves #198
Resolves #191
> Add followers to profile, download button and cheeps to the profile page

- .devcontainer/Dockerfile
- .devcontainer/ThankYou.md
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .devcontainer/mssql/installSQLtools.sh
- .devcontainer/mssql/postCreateCommand.sh
- .devcontainer/mssql/setup.sql
- src/Chirp.Web/appsettings.json
to make the experience seamless
Docker is awesome and dev containers are magic
Resolves #176
> Added dev container support and made some post create commands

- src/Chirp.Web/Pages/UserTimeline.cshtml
- src/Chirp.Web/Pages/UserTimeline.cshtml.cs
Added temp fix until we can figure out why bug occurs (Low prio).
Resolves #213
> Ensured usertimeline's page numbers fits.

- src/Chirp.Web/Pages/Public.cshtml
- src/Chirp.Web/Pages/Public.cshtml.cs
- src/Chirp.Web/Pages/UserTimeline.cshtml
- src/Chirp.Web/Pages/UserTimeline.cshtml.cs
> added youtube embeds in cheeps

- src/Chirp.Web/Pages/Public.cshtml
- src/Chirp.Web/Pages/UserTimeline.cshtml
- src/Chirp.Web/wwwroot/css/style.css
Changes input in cheep post form from input to textarea. This fixes the shit + enter = open new window bug. And allows for making new lines in cheeps.
Resolves #232
> Fix shift enter bug

- src/Chirp.Core/ICheepRepository.cs
- src/Chirp.Infrastructure/ChirpRepository/CheepRepository.cs
- src/Chirp.Web/Pages/Hashtag.cshtml
- src/Chirp.Web/Pages/Hashtag.cshtml.cs
- src/Chirp.Web/Pages/Public.cshtml
- src/Chirp.Web/Pages/Public.cshtml.cs
- src/Chirp.Web/Pages/UserTimeline.cshtml
- src/Chirp.Web/Pages/UserTimeline.cshtml.cs
- src/Chirp.Web/wwwroot/css/style.css
Resolves #237
Resolves #243 
There's a bit more code duplication in the works, so #215 should probably be worked on soon to reduce the redundancy.
Otherwise, adding ugc (user generated content) to the hashtags links is a bit of an overkill for this assignment, but its great for SEO if there's a future for the app.
> Hashtags in cheeps

- src/Chirp.Web/Pages/Public.cshtml
- src/Chirp.Web/Pages/UserTimeline.cshtml
- src/Chirp.Web/wwwroot/css/style.css
> Styling upgrades to like and dislike buttons

- src/Chirp.Core/CheepDTO.cs
- src/Chirp.Infrastructure/ChirpRepository/ReactionRepository.cs
- test/Chirp.Razor.Tests/IntegrationTests.cs
resolves #247
Added three test for reactions
> Test reaction

- src/Chirp.Web/Pages/BasePageModel.cs
- src/Chirp.Web/Pages/BindableClasses.cs
- src/Chirp.Web/Pages/Hashtag.cshtml
- src/Chirp.Web/Pages/Public.cshtml
- src/Chirp.Web/Pages/UserProfile.cshtml.cs
- src/Chirp.Web/Pages/UserTimeline.cshtml
- src/Chirp.Web/Pages/UserTimeline.cshtml.cs
- src/Chirp.Web/PagesData.cs
- src/Chirp.Web/Program.cs
1: UserProfile.cshtml.cs now properly inherits from basepagemodel, joining all other chirp.web pages in their proper hierarchy.
2: unneeded comments and already done todo comments deleted.
3: unneeded usings removed
> All chirp.web pages now inheriting properly and small comment fixes

- src/Chirp.Core/IAuthorRepository.cs
- src/Chirp.Core/ICheepRepository.cs
- src/Chirp.Core/IReactionRepository.cs
- src/Chirp.Core/IUserRepository.cs
- src/Chirp.Infrastructure/ChirpRepository/AuthorRepository.cs
- src/Chirp.Infrastructure/ChirpRepository/CheepRepository.cs
- src/Chirp.Infrastructure/ChirpRepository/ReactionRepository.cs
- src/Chirp.Infrastructure/ChirpRepository/UserRepository.cs
- test/Chirp.Razor.Tests/IntegrationTests.cs
Changes the access modifiers for some repo methods from `public` to `private` when the method should not be accessable outside the repo class
> Change access modifiers

- report.md
- report_diagrams/UML_activity_diagrams/azure_pipeline_UML_act.puml
- report_diagrams/UML_activity_diagrams/build_test_UML_act.puml
- report_diagrams/UML_activity_diagrams/build_test_release_UML_act.puml
- report_diagrams/UML_activity_diagrams/build_test_release_UML_seq.puml
- report_diagrams/UML_activity_diagrams/playwright_UML_act.puml
- report_diagrams/UML_sequence_diagrams/azure_pipeline_UML_seq.puml
- report_diagrams/UML_sequence_diagrams/build_test_release_UML_seq.puml
Just a merge to make some better structure on main
> Report Theis to main to create proper folder structure
